//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillHistory
    {
        public System.Guid Id { get; set; }
        public System.Guid PatientId { get; set; }
        public System.Guid OPDHistoryId { get; set; }
        public int ReceiptNumber { get; set; }
        public Nullable<int> PrintCopys { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> LastPrintedBy { get; set; }
        public Nullable<System.DateTime> LastPrintedOn { get; set; }
    
        public virtual PatientDetail PatientDetail { get; set; }
        public virtual OPDHistory OPDHistory { get; set; }
    }
}
