//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPDHistoryUpdate
    {
        public System.Guid Id { get; set; }
        public System.Guid OPDHistoryId { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public string UpdatedField { get; set; }
        public string UpdatedValue { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string PreviousValue { get; set; }
    
        public virtual OPDHistory OPDHistory { get; set; }
    }
}
