//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPDHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPDHistory()
        {
            this.Amount = 0.00m;
            this.PaidAmount = 0.00m;
            this.DueAmount = 0.00m;
            this.LabTestingAmount = 0.00m;
            this.TotalAmount = 0.00m;
            this.PatientHistories = new HashSet<PatientHistory>();
            this.BillHistories = new HashSet<BillHistory>();
            this.OPDHistoryUpdates = new HashSet<OPDHistoryUpdate>();
            this.TPLabPatientMappings = new HashSet<TPLabPatientMapping>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> PatientId { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<System.DateTime> InTime { get; set; }
        public Nullable<System.DateTime> OutTime { get; set; }
        public Nullable<bool> IsCharity { get; set; }
        public Nullable<System.Guid> StatusId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<decimal> DueAmount { get; set; }
        public Nullable<System.Guid> ReceivedBy { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<bool> IsLabCharity { get; set; }
        public string Diagnose { get; set; }
        public string Madicines { get; set; }
        public Nullable<decimal> LabTestingAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> ECGAmount { get; set; }
        public Nullable<decimal> XRAYAmount { get; set; }
        public Nullable<System.Guid> ConsultingDoctorId { get; set; }
        public Nullable<System.Guid> ThirdPartyLabId { get; set; }
        public Nullable<decimal> ThirdPartyLabAmoumt { get; set; }
        public Nullable<bool> IsECG { get; set; }
        public Nullable<bool> IsXRAY { get; set; }
        public Nullable<int> NumberofXRAY { get; set; }
        public Nullable<int> IsFollowUp { get; set; }
    
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientHistory> PatientHistories { get; set; }
        public virtual PatientDetail PatientDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillHistory> BillHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPDHistoryUpdate> OPDHistoryUpdates { get; set; }
        public virtual LabDetail LabDetail { get; set; }
        public virtual DoctorDetail DoctorDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TPLabPatientMapping> TPLabPatientMappings { get; set; }
    }
}
