//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPLabPatientMapping
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> OPDHistoryId { get; set; }
        public Nullable<System.Guid> LabId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.Guid> Createdby { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    
        public virtual LabDetail LabDetail { get; set; }
        public virtual OPDHistory OPDHistory { get; set; }
    }
}
